### ISSUE TITLE
Cannot open gapps after upgrading to android13

### ISSUE THREAD

**Issue by shuaixr** [wacko1805/MagiskGapps#24]
Can't open gapps after upgrading to Android 13, I tried both 10.16.2022 and 24.2.23.
I tried to capture the crash log of Google play:
```
05-29 19:42:37.563 E/AndroidRuntime( 4336): FATAL EXCEPTION: main
05-29 19:42:37.563 E/AndroidRuntime( 4336): Process: com.android.vending, PID: 4336
05-29 19:42:37.563 E/AndroidRuntime( 4336): java.lang.RuntimeException: Unable to create application com.google.android.finsky.application.classic.ClassicApplication: java.lang.RuntimeException: Failed to load configurations for FinskyApp
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7156)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2263)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Looper.loopOnce(Looper.java:211)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Looper.loop(Looper.java:300)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.app.ActivityThread.main(ActivityThread.java:8294)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at java.lang.reflect.Method.invoke(Native Method)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
05-29 19:42:37.563 E/AndroidRuntime( 4336): Caused by: java.lang.RuntimeException: Failed to load configurations for FinskyApp
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at flq.g(PG:32)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at flq.onCreate(PG:5)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1286)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7150)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	... 9 more
05-29 19:42:37.563 E/AndroidRuntime( 4336): Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at afyw.s(PG:3)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at afyw.get(PG:9)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at agjw.ag(PG:1)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at flq.g(PG:25)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	... 12 more
05-29 19:42:37.563 E/AndroidRuntime( 4336): Caused by: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Parcel.createException(Parcel.java:2995)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Parcel.readException(Parcel.java:2978)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Parcel.readException(Parcel.java:2920)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1113)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2712)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2660)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at abax.k(PG:2)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at abax.g(PG:2)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at adrc.<init>(Unknown Source:5)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at adrd.j(Unknown Source:6)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at fjk.a(PG:9)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at agoa.run(PG:48)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at aila.run(PG:2)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at ailc.run(PG:34)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at yge.run(PG:27)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at java.lang.Thread.run(Thread.java:1012)
05-29 19:42:37.563 E/AndroidRuntime( 4336): Caused by: android.os.RemoteException: Remote stack trace:
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:376)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.content.IContentService$Stub.onTransact(IContentService.java:517)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Binder.execTransactInternal(Binder.java:1285)
05-29 19:42:37.563 E/AndroidRuntime( 4336): 	at android.os.Binder.execTransact(Binder.java:1249)
05-29 19:42:37.563 E/AndroidRuntime( 4336): ```

**Comment by wacko1805** [comment]
What device/rom?

**Comment by shuaixr** [comment]
> What device/rom?

Device:Redmi Note 11 5G (evergo)
Rom:MIUI V14.0.2.0.TGBCNXM

After installing MagiskGapps, there is no GoogleServiceFramework in system, and manual installation prompts the system is not compatible

**Comment by wacko1805** [comment]
Due to many issues with MIUI and not having any mi devices to test on, I made classed MagiskGApps as not compatible with MIUI.
