### ISSUE TITLE
Some Games, Especially those with OBB fail to install

### ISSUE THREAD

**Issue by NightHammer1000** [wacko1805/MagiskGapps#8]
Games like Escapist 2 or Call of Duty Mobile fail while installing the OBB Part.

Installing the App manually or throug APKPure XAPK works flawlessly. So I suspect this is a Issue with the Gapps Magisk Module.

Here the Logcat of the escapist install:

```
2022-03-14 10:42:59.165 24255-17297/? E/Finsky:background: [5134] jjo.t(72): Failed to create downloadStatus files.
    java.io.IOException: Can't create  file:///storage/emulated/0/Android/obb/com.android.vending/com.team17.escapists2/temp.main.542914.com.team17.escapists2.obb
        at jjo.t(PG:71)
        at icq.c(PG:19)
        at leu.a(PG:23)
        at akws.c(PG:2)
        at akiv.c(PG:2)
        at aksk.b(PG:2)
        at aksn.a(PG:3)
        at aknm.run(PG:2)
        at aksj.run(PG:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1008)
        at jjo.t(PG:36)
        at icq.c(PG:19) 
        at leu.a(PG:23) 
        at akws.c(PG:2) 
        at akiv.c(PG:2) 
        at aksk.b(PG:2) 
        at aksn.a(PG:3) 
        at aknm.run(PG:2) 
        at aksj.run(PG:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2022-03-14 10:42:59.168 25962-25962/? W/Finsky: [2] kie.x(2): Installer::IT: Cleanup running installation of com.team17.escapists2 (..obb_main) (isid: nt3vMyNSSaq_ppfjKzG9UQ)
2022-03-14 10:42:59.176 25962-25962/? I/Finsky: [2] khi.ab(2): Installer: stopping tracking of task: com.team17.escapists2 (isid: nt3vMyNSSaq_ppfjKzG9UQ)
2022-03-14 10:42:59.177 25962-25962/? I/Finsky: [2] khi.ab(2): Installer: stopping tracking of task: com.team17.escapists2 (isid: nt3vMyNSSaq_ppfjKzG9UQ)
2022-03-14 10:42:59.177 25962-25962/? I/Finsky: [2] khi.U(18): Installer: Notifying status update. package=com.team17.escapists2, status=DOWNLOAD_ERROR, isid=nt3vMyNSSaq_ppfjKzG9UQ
2022-03-14 10:42:59.180 25962-16968/? I/Finsky: [5471] kpr.E(2): IQ: Notifying installation update. [Package:com.team17.escapists2, isid:nt3vMyNSSaq_ppfjKzG9UQ], status=DOWNLOAD_ERROR
2022-03-14 10:42:59.183 25962-26090/? I/Finsky: [5128] ofr.F(4): PackageInstaller: Abandoned the session for com.team17.escapists2, sessionId: 230629558
2022-03-14 10:42:59.194 25962-25962/? I/Finsky: [2] pwj.lE(4): PIM: Handling install package event for: com.team17.escapists2 status:  DOWNLOAD_ERROR
2022-03-14 10:42:59.194 25962-25962/? I/Finsky: [2] pwj.lE(5): PIM: Stopping icon download for com.team17.escapists2
2022-03-14 10:42:59.194 25962-25962/? I/Finsky: [2] pwh.a(1): Canceling bitmap for com.team17.escapists2
2022-03-14 10:42:59.207 25962-25998/? I/Finsky: [5094] flb.b(3): AU2: Failure History successfully updated for package com.team17.escapists2, attempting to upgrade to version 542914 with install reason SINGLE_INSTALL and status_code 5200
2022-03-14 10:42:59.224 25962-25962/? I/Finsky: [2] jjo.C(7): Selecting account [W9tjBmyCGkkRuCJYIF7ROMq_Uw3flXpsQvgfVEJU8mY] for package com.team17.escapists2. overriding=[true]
2022-03-14 10:42:59.227 25962-25962/? I/Finsky: [2] jjo.C(7): Selecting account [W9tjBmyCGkkRuCJYIF7ROMq_Uw3flXpsQvgfVEJU8mY] for package com.team17.escapists2. overriding=[true]
2022-03-14 10:42:59.240 25962-25962/? I/Finsky: [2] jjo.C(7): Selecting account [W9tjBmyCGkkRuCJYIF7ROMq_Uw3flXpsQvgfVEJU8mY] for package com.team17.escapists2. overriding=[true]
2022-03-14 10:42:59.244 25962-25962/? I/Finsky: [2] jjo.C(7): Selecting account [W9tjBmyCGkkRuCJYIF7ROMq_Uw3flXpsQvgfVEJU8mY] for package com.team17.escapists2. overriding=[true]

```

**Comment by NightHammer1000** [comment]
com.android.vending is missing in the obb Folder.
If i create it Manually the whole playstore crashes while installing the Game.
Could it be that there is some kind of mount missing?

**Comment by Xabellee** [comment]
I have the same problem. Do you know any workaround?

**Comment by NightHammer1000** [comment]
Yeah. 
https://litegapps.github.io/
LiteGapps++ as the Magisk Version work flawless.
Much better than this package here.

**Comment by wacko1805** [comment]
Closed as this relates to old MagiskGApps varients.
